"""
PM Agent Platform - Core Package

Provides foundational components for multi-agent platform:
- Configuration management (Pydantic Settings)
- Database layer (SQLAlchemy 2.0 async)
- LLM integration (YandexGPT)
- Tool system (@platform_tool decorator)
- Custom exceptions
- Database models
"""

__version__ = "0.1.0"

from core import config, db, exceptions, llm, logging, models, prompts, tools
from core.config import (
    AppConfig,
    Config,
    DatabaseConfig,
    LLMConfig,
    RuntimeConfig,
    TrackerConfig,
    YandexConfig,
    get_config,
    reload_config,
    set_config,
)
from core.db import (
    Checkpointer,
    close_engine,
    create_db_engine,
    get_engine,
    get_session,
    get_session_factory,
    health_check,
    reset_engine,
)
from core.exceptions import (
    A2AError,
    AgentError,
    AutonomyError,
    ConfigError,
    ConfirmError,
    ConfirmRejectedError,
    ConfirmTimeoutError,
    CoreError,
    DBError,
    LLMError,
    RegistryError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolValidationError,
)
from core.llm import (
    LLMClient,
    LLMResponse,
    Message,
    TokenUsage,
    ToolCall,
    complete,
)
from core.logging import (
    JSONFormatter,
    configure_logging,
    get_logger,
    get_trace_id,
    set_trace_id,
    timed,
)
from core.models import (
    Action,
    ActionFeedback,
    AgentInstance,
    AgentSpec,
    Base,
    Confirm,
    Organization,
    RuntimeConfigModel,
    ScheduledJob,
    Team,
    Trace,
)
from core.prompts import (
    PM_AGENT_SYSTEM_PROMPT,
    ROLE_ASSISTANT,
    ROLE_SYSTEM,
    ROLE_USER,
    format_confirm_prompt,
    format_error_message,
    format_tool_descriptions,
)
from core.tools import (
    Tool,
    ToolParameter,
    ToolRegistry,
    get_registry,
    platform_tool,
)

__all__ = [
    "__version__",
    "config",
    "db",
    "exceptions",
    "llm",
    "logging",
    "models",
    "prompts",
    "tools",
    "Config",
    "DatabaseConfig",
    "YandexConfig",
    "TrackerConfig",
    "LLMConfig",
    "AppConfig",
    "RuntimeConfig",
    "get_config",
    "reload_config",
    "set_config",
    "create_db_engine",
    "get_engine",
    "get_session",
    "get_session_factory",
    "health_check",
    "close_engine",
    "reset_engine",
    "Checkpointer",
    "Message",
    "ToolCall",
    "TokenUsage",
    "LLMResponse",
    "LLMClient",
    "complete",
    "Tool",
    "ToolParameter",
    "ToolRegistry",
    "platform_tool",
    "get_registry",
    "CoreError",
    "ConfigError",
    "DBError",
    "LLMError",
    "ToolError",
    "ToolNotFoundError",
    "ToolValidationError",
    "ToolExecutionError",
    "ConfirmError",
    "ConfirmTimeoutError",
    "ConfirmRejectedError",
    "AutonomyError",
    "AgentError",
    "A2AError",
    "RegistryError",
    "JSONFormatter",
    "get_logger",
    "set_trace_id",
    "get_trace_id",
    "configure_logging",
    "timed",
    "PM_AGENT_SYSTEM_PROMPT",
    "format_tool_descriptions",
    "format_confirm_prompt",
    "format_error_message",
    "ROLE_SYSTEM",
    "ROLE_USER",
    "ROLE_ASSISTANT",
    "Base",
    "Organization",
    "Team",
    "AgentSpec",
    "AgentInstance",
    "Action",
    "Trace",
    "Confirm",
    "RuntimeConfigModel",
    "ScheduledJob",
    "ActionFeedback",
]
