"""
PM Agent Platform - Core Package

Provides foundational components for multi-agent platform:
- Configuration management (Pydantic Settings)
- Database layer (SQLAlchemy 2.0 async)
- LLM integration (YandexGPT)
- Tool system (@platform_tool decorator)
- Custom exceptions
- Database models
"""

__version__ = "0.1.0"

from core import (
    agent,
    bot,
    config,
    db,
    effective_config,
    entry_point,
    exceptions,
    llm,
    logging,
    metrics,
    models,
    prompts,
    react,
    registry,
    scheduler,
    seed,
    tools,
)
from core.agent import (
    AgentResponse,
    BaseAgent,
    LLMSettings,
)
from core.bot import BaseBot
from core.config import (
    AppConfig,
    Config,
    DatabaseConfig,
    LLMConfig,
    RuntimeConfig,
    TrackerConfig,
    YandexConfig,
    get_config,
    reload_config,
    set_config,
)
from core.db import (
    Checkpointer,
    close_engine,
    create_all_tables,
    create_db_engine,
    get_engine,
    get_session,
    get_session_factory,
    health_check,
    reset_engine,
)
from core.effective_config import EffectiveAgentConfig, build_effective_config
from core.entry_point import EntryPoint
from core.exceptions import (
    A2AError,
    AgentError,
    AutonomyError,
    ConfigError,
    ConfirmError,
    ConfirmRejectedError,
    ConfirmTimeoutError,
    CoreError,
    DBError,
    LLMError,
    RegistryError,
    ToolError,
    ToolExecutionError,
    ToolNotFoundError,
    ToolValidationError,
)
from core.llm import (
    LLMClient,
    LLMResponse,
    Message,
    TokenUsage,
    ToolCall,
    complete,
)
from core.logging import (
    JSONFormatter,
    configure_logging,
    get_logger,
    get_trace_id,
    set_trace_id,
    timed,
)
from core.metrics import (
    agent_confirms_pending,
    agent_traces_total,
    db_pool_checked_out,
    external_latency_seconds,
    external_requests_total,
    llm_latency_seconds,
    llm_requests_total,
    llm_tokens_total,
    tool_executions_total,
    tool_latency_seconds,
    track_tool,
)
from core.models import (
    Action,
    ActionFeedback,
    AgentInstance,
    AgentSpec,
    Base,
    Confirm,
    ConsoleSession,
    Organization,
    RuntimeConfigModel,
    ScheduledJob,
    Team,
    Trace,
    User,
)
from core.prompts import (
    PM_AGENT_SYSTEM_PROMPT,
    ROLE_ASSISTANT,
    ROLE_SYSTEM,
    ROLE_USER,
    format_confirm_prompt,
    format_error_message,
    format_tool_descriptions,
)
from core.react import AgentResult, PendingConfirm, ReActRunner
from core.registry import BotRegistry, get_bot_registry
from core.scheduler import SchedulerDaemon, compute_next_run
from core.seed import ensure_default_team
from core.tools import (
    Tool,
    ToolParameter,
    ToolRegistry,
    get_registry,
    platform_tool,
)
from core.tracker import TrackerClient, TrackerError
from core.tracker_tools import (
    tracker_close_issue,
    tracker_comment_issue,
    tracker_create_issue,
    tracker_find_issues,
    tracker_get_issue,
    tracker_get_queue_meta,
    tracker_link_issues,
    tracker_list_transitions,
    tracker_patch_issue,
    tracker_search_issues,
    tracker_transition_issue,
    tracker_update_followers,
    tracker_update_issue,
)

__all__ = [
    "__version__",
    "agent",
    "bot",
    "config",
    "db",
    "entry_point",
    "exceptions",
    "llm",
    "logging",
    "metrics",
    "models",
    "prompts",
    "registry",
    "effective_config",
    "scheduler",
    "seed",
    "tools",
    "LLMSettings",
    "BaseAgent",
    "AgentResponse",
    "BaseBot",
    "EntryPoint",
    "BotRegistry",
    "get_bot_registry",
    "react",
    "TrackerClient",
    "TrackerError",
    "tracker_get_queue_meta",
    "tracker_find_issues",
    "tracker_get_issue",
    "tracker_search_issues",
    "tracker_list_transitions",
    "tracker_create_issue",
    "tracker_patch_issue",
    "tracker_update_issue",
    "tracker_update_followers",
    "tracker_transition_issue",
    "tracker_link_issues",
    "tracker_comment_issue",
    "tracker_close_issue",
    "ReActRunner",
    "AgentResult",
    "PendingConfirm",
    "Config",
    "DatabaseConfig",
    "YandexConfig",
    "TrackerConfig",
    "LLMConfig",
    "AppConfig",
    "RuntimeConfig",
    "get_config",
    "reload_config",
    "set_config",
    "create_db_engine",
    "get_engine",
    "get_session",
    "get_session_factory",
    "create_all_tables",
    "health_check",
    "close_engine",
    "reset_engine",
    "Checkpointer",
    "EffectiveAgentConfig",
    "build_effective_config",
    "SchedulerDaemon",
    "compute_next_run",
    "ensure_default_team",
    "Message",
    "ToolCall",
    "TokenUsage",
    "LLMResponse",
    "LLMClient",
    "complete",
    "llm_requests_total",
    "llm_latency_seconds",
    "llm_tokens_total",
    "tool_executions_total",
    "tool_latency_seconds",
    "external_requests_total",
    "external_latency_seconds",
    "db_pool_checked_out",
    "agent_traces_total",
    "agent_confirms_pending",
    "track_tool",
    "Tool",
    "ToolParameter",
    "ToolRegistry",
    "platform_tool",
    "get_registry",
    "CoreError",
    "ConfigError",
    "DBError",
    "LLMError",
    "ToolError",
    "ToolNotFoundError",
    "ToolValidationError",
    "ToolExecutionError",
    "ConfirmError",
    "ConfirmTimeoutError",
    "ConfirmRejectedError",
    "AutonomyError",
    "AgentError",
    "A2AError",
    "RegistryError",
    "JSONFormatter",
    "get_logger",
    "set_trace_id",
    "get_trace_id",
    "configure_logging",
    "timed",
    "PM_AGENT_SYSTEM_PROMPT",
    "format_tool_descriptions",
    "format_confirm_prompt",
    "format_error_message",
    "ROLE_SYSTEM",
    "ROLE_USER",
    "ROLE_ASSISTANT",
    "Base",
    "Organization",
    "User",
    "ConsoleSession",
    "Team",
    "AgentSpec",
    "AgentInstance",
    "Action",
    "Trace",
    "Confirm",
    "RuntimeConfigModel",
    "ScheduledJob",
    "ActionFeedback",
]
