#!/usr/bin/env python3
"""
Audit Yandex Tracker queue fields and write docs/tracker_queue_<QUEUE>.md

Run from packages/core/:
    python scripts/audit_tracker_queue.py
    python scripts/audit_tracker_queue.py DARKHORSE
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

for line in (Path(__file__).resolve().parents[1] / ".env").read_text().splitlines():
    line = line.strip()
    if not line or line.startswith("#") or "=" not in line:
        continue
    k, _, v = line.partition("=")
    os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))

from core.config import get_config  # noqa: E402
from core.tracker import TrackerClient  # noqa: E402


async def main(queue: str | None = None) -> None:
    cfg = get_config().tracker
    queue_key = queue or cfg.tracker_queue
    async with TrackerClient() as client:
        meta = await client.get_queue_meta(queue_key)
        raw_queue = await client.get_queue(queue_key)
        local = await client.get_queue_local_fields(queue_key)

    out_dir = Path(__file__).resolve().parents[2] / "docs"
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path = out_dir / f"tracker_queue_{queue_key}.md"
    json_path = out_dir / f"tracker_queue_{queue_key}.json"
    issue_types_json = json.dumps(meta.get("issue_types"), ensure_ascii=False, indent=2)
    priorities_json = json.dumps(meta.get("priorities"), ensure_ascii=False, indent=2)
    local_fields_json = json.dumps(meta.get("local_fields"), ensure_ascii=False, indent=2)

    md_path.write_text(
        f"# Tracker queue: {queue_key}\n\n"
        f"Generated by `audit_tracker_queue.py`.\n\n"
        f"## Summary\n\n"
        f"- Name: {meta.get('queue_name')}\n"
        f"- Issue types: {len(meta.get('issue_types', []))}\n"
        f"- Priorities: {len(meta.get('priorities', []))}\n"
        f"- Local fields: {len(meta.get('local_fields', []))}\n\n"
        f"## Agent hint\n\n{meta.get('hint')}\n\n"
        f"## Issue types\n\n```json\n{issue_types_json}\n```\n\n"
        f"## Priorities\n\n```json\n{priorities_json}\n```\n\n"
        f"## Local fields\n\n```json\n{local_fields_json}\n```\n",
        encoding="utf-8",
    )
    json_path.write_text(
        json.dumps(
            {"meta": meta, "queue": raw_queue, "local_fields_raw": local},
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {md_path}")
    print(f"Wrote {json_path}")


if __name__ == "__main__":
    q = sys.argv[1] if len(sys.argv) > 1 else None
    asyncio.run(main(q))
